### ISSUE TITLE
Add option for slashed zero

### ISSUE THREAD

**Issue by stackingsaunter** [lauridskern/open-runde#2]
I love your font I think we'd love to switch from Inter on getalby.com!

But we really need to have slashed zero option for numerics. Would you be able to add it?

**Comment by jankoegel** [comment]
I'm a colleague of Jakub's from @getalby.

Here's a quick demo of what we're trying to get to work:
slashed zeroes in a browser via CSS's `font-variant-numeric: slashed-zero` attribute (https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric):
https://codepen.io/jankoegel/pen/wvQQzmz?editors=1100

JFYI:
it seems the unicode slashed zero (e.g. copyable from here: https://en.wikipedia.org/wiki/Slashed_zero) is broken the same way in Runde as it is in Inter when rendered in a browser:

left working version that we currently use with Inter, right: broken unicode slashed zero (all rendered in a browser):
![image](https://github.com/lauridskern/open-runde/assets/100707419/818872d2-f670-415f-949a-29276b6d731b)

it seems that Runde contains some slashed zero glyphs. For lack of better tooling (not a type designer), I used https://fontdrop.info and found:
![image](https://github.com/lauridskern/open-runde/assets/100707419/77063c61-1aa6-4a21-a912-0d6c2ac27e6e)

Hope this helps & cheers.

**Comment by lauridskern** [comment]
I added a slashed zero in the latest release. 
You should be able to use `font-feature-settings: 'zero' 1;` in CSS.

**Comment by stackingsaunter** [comment]
Excellent, thank you

**Comment by jankoegel** [comment]
Works fine with `font-variant-numeric: slashed-zero`:
https://codepen.io/jankoegel/pen/RwqEaxG?editors=1100

Thanks very much!
